---
- name: install npm.
  apt:
    name: npm

- name: mkdir for nvm install.
  become: false
  file:
    path: "{{ ansible_tmpDir }}/nvm"
    state: "directory"

- name: Download nvm install.sh.
  get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh"
    dest: "{{ ansible_tmpDir }}/nvm/"
    mode: 0755

- name: install nvm.
  shell: "{{ ansible_tmpDir }}/nvm/install.sh"
  become: false

- name: install node with using nvm.
  shell: /bin/bash -lc "{{ ansible_home }}/.nvm/nvm.sh; nvm install --lts; nvm alias default 'lts/*'"
  become: false
