---
- name: install python3-dev
  apt:
    name: "python3-dev"

- name: mkdir for pyenv
  become: false
  file:
    path: "{{ ansible_home }}/.pyenv"
    state: directory

- name: install pyenv
  become: false
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ ansible_home }}/.pyenv"
