---
- name: install zsh
  apt:
    name: "zsh"

- name: set zsh as default shell
  command: >
    /bin/bash -lc
    "chsh -s $(which zsh) {{ ansible_user }}"

- name: mkdir for zplugin
  become: false
  file:
    path: "{{ ansible_tmpDir }}/zplugin"
    state: directory

- name: Download zplugin install.sh
  become: false
  get_url:
    url: https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh
    dest: "{{ ansible_tmpDir }}/zplugin"
    mode: +x

- name: intall zplugin
  become: false
  shell: "{{ ansible_tmpDir }}/zplugin/install.sh"
