---
- name: add apt repository to install Firefox Developer Edition
  apt_repository:
    repo: "ppa:ubuntu-mozilla-daily/firefox-aurora"
    state: present

- name: install Firefox Developer Edition
  apt:
    name: firefox
    update_cache: yes
    install_recommends: yes

- name: install chrome browser.
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
